import Head from "next/head";
import { TechContainerBg } from "@components/components/TechContainerBg";
import { MintForm } from "@components/components/MintForm";


export default function Home() {
  return (
    <>
      <Head>
        <title>Op_punk_</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="description"
          content="Unleash your punk spirit on Optimism: Claim and manage your unique subname under oppunk.eth."
        />
        <meta property="og:title" content={`Oppunk.eth on Namespace`} />
        <meta
          property="og:description"
          content="Unleash your punk spirit on Optimism: Claim and manage your unique subname under oppunk.eth."
        />
        <meta
          property="og:image"
          content="https://punks.namespace.ninja/preview.png"
        />
        <meta property="og:image:width" content="1911" />
        <meta property="og:image:height" content="670" />
        <meta name="twitter:card" />
        <meta name="twitter:title" content="Namespace" />
        <meta
          name="twitter:description"
          content="Unleash your punk spirit on Optimism: Claim and manage your unique subname under oppunk.eth."
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="twitter:image:src"
          content="https://punks.namespace.ninja/preview.png"
        />
        <meta name="theme-color" content="#5C61FF" />
      </Head>
      <MintForm/>
    </>
  );
}