import Head from "next/head";
import { TechContainerBg } from "@components/components/TechContainerBg";
import { MintForm } from "@components/components/MintForm";


export default function Home() {
  return (
    <>
      <Head>
        <title>OpPunk - Namespace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MintForm/>
    </>
  );
}
